sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: g++
      env:
        - LOCAL_CC=gcc-9
        - LOCAL_CXX=g++-9
        - JOBNAME=gcc
      before_install:
        - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        - sudo apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main'
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        - sudo apt-get install -qq gcc-9 g++-9;
        - sudo apt-get install -qq libboost-all-dev libssl-dev lcov libsqlite3-dev libmicrohttpd-dev cmake libcurl4-openssl-dev

        - sudo apt-get install software-properties-common
        - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
        - sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.netcologne.de/mariadb/repo/10.4/ubuntu bionic main'
        - sudo apt-get update -qq;
        - sudo apt-get remove libmysqlclient-dev mysql-server;
        - sudo apt-get install -qq libmariadb-dev mariadb-server;


    - compiler: clang++
      env:
        - LOCAL_CC=clang-9
        - LOCAL_CXX=clang++-9
        - JOBNAME=clang
        - CXXFLAGS=--stdlib=libc++
      before_install:
        - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        - sudo apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main'
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -;
        - sudo echo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main >> /etc/apt/sources.list;
        - sudo apt-get update -qq;
        - sudo apt-get install -qq clang-9 libc++-9-dev libc++abi-9-dev libclang-9-dev;
        - sudo apt-get install -qq libboost-all-dev libssl-dev lcov libsqlite3-dev libmicrohttpd-dev cmake libcurl4-openssl-dev

        - sudo apt-get install software-properties-common
        - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
        - sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror.netcologne.de/mariadb/repo/10.4/ubuntu bionic main'
        - sudo apt-get update -qq;
        - sudo apt-get remove libmysqlclient-dev mysql-server;
        - sudo apt-get install -qq libmariadb-dev mariadb-server;

    # std::filesystem Need macos 10.15. Not yet on travis.
    # - os: osx
    #   osx_image: xcode11.2
    #   compiler: clang
    #   env: COMPILER=clang++
    #   before_install:
    #     - brew update
    #     - brew install boost sqlite mariadb cmake libmicrohttpd
  
before_script:
    - cd $HOME/build/$TRAVIS_REPO_SLUG
    - mkdir -p build 
    - cd build 
    - cmake .. -DCMAKE_CXX_COMPILER=${LOCAL_CXX} -DCMAKE_INSTALL_PREFIX=$HOME/local

script:
    - cd $HOME/build/$TRAVIS_REPO_SLUG/build 
    - bash ../libraries/sql/tests/mysql_test_server.sh start
    - make all
    - ./libraries/http_backend/tests/serve_directory
    - make all test

after_script:
    echo after_script
